### ISSUE TITLE
Switch ERROR for FAILURE

### ISSUE THREAD

**Issue by haffs** [alexwebr/salsa20#3]
--- a/cli.c
+++ b/cli.c
@@ -26,7 +26,7 @@ int main(int argc, char *argv[])
     uint8_t c = in;
     // Encrypt a single character at a time
     //                          key     128-bit key                 nonce  encrypt one byte
-    if (s20_crypt((uint8_t *) argv[1], S20_KEYLEN_128, (uint8_t *) argv[2], si++, &c, 1) == S20_ERROR)
+    if (s20_crypt((uint8_t *) argv[1], S20_KEYLEN_128, (uint8_t *) argv[2], si++, &c, 1) == S20_FAILURE)
       puts("Error: encryption failed");
     putchar(c);
   }

**Comment by alexwebr** [comment]
Derp. Thanks, fixed in 0d337aa49a6a887d4930750f63f1e5a5ddf3055f.
